# Generated by Django 4.2.3 on 2023-07-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Blog', '0003_auto_20210414_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='vaccation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_name', models.CharField(default='true', max_length=400)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('holiday_from', models.DateField()),
                ('holiday_to', models.DateField()),
            ],
        ),
    ]
