# Generated by Django 4.2.3 on 2023-07-07 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0004_alter_employee_ph'),
        ('App_Blog', '0004_vaccation'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccation',
            name='team_mate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cutiya', to='App_Login.employee'),
            preserve_default=False,
        ),
    ]
