# Generated by Django 4.2.3 on 2023-07-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='true', max_length=230)),
                ('dept', models.CharField(max_length=4)),
                ('ph', models.IntegerField(max_length=10)),
            ],
        ),
    ]
